name: given_when_then
description: A Flutter package to enable code reuse while making tests more readable.
version: 0.2.0
homepage: https://github.com/eBay/flutter_glove_box/
repository: https://github.com/eBay/flutter_glove_box/tree/master/packages/given_when_then
issue_tracker: https://github.com/eBay/flutter_glove_box/issues

environment:
  sdk: 3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0